apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secret-values
  namespace: n8n
spec:
  encryptedData:
    values.yaml: AgCEbolze+IfOZ/lIfW7psOOJbdJzhQP98m9nQEx//5+Imz4/Z0PSwY/f4REbcDqqRgPyx05zRKOjGWl16h/H7LXwVNvLM6EdMBhy3D7JTRwgZ4J1cKGY/+Rr+JjBUREG6KtsH8uE+0me6xYBb1P6mXWMVWLiHePp3ptGuNSrKCiowbu14M4mZVwMZsrRjbespaQ7PGSgimCXTri4C5IuSsYLYct9/e+tdYGRsGm46p9zXeDJBrTXX8dUKC467STFirZZbubBlbAnCUAMmgeoU7Envuc5V2x/f3jkLDdOXJ1+dcOhIfiydxYtIji7kCWlHHxMpMZWUBhjT2M/ifcFRENkRbyXFO56b3dIXSwp/1APVkQDPWCDFi8GLnZwJ3xKnGhF+x9zjZe2xHLdgeBbV6fqbXnP13CUIeYlntRys0w81PZAV/gEZHzlXBD1g9RX77BoCbzgkv4UnHfMLHWEh9UPCzrcrPPtH+AD/ZQnQuDrCV6KLKWc+FUVWLOCTdwvRkKxQoKG5im7x9Hjp19zQ3yIxV7lMTbgXYFrFWIrHxCcxXLf2PfMD7nALDwD+itzHGZ8R5KYYvO8c2I+jMLxPpc4jefgNf2tL8ngZotm6aiIG3BOAHzbqIb/DZ+Kkw9yuBLewfTso6hHqw6cwk14tn7AlwHdbtAYn81SlOG7bnWE+DIgYvZ7eURFvryZovyE0HrC6cGSWiYAN0KqBPIsfQZ3Z/l3AXymlxs+csd5giszOJE73fXn8WaoqYsYUCeP5abkoz+G9aKFfmSkoXN
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secret-values
      namespace: n8n