apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secret-values
  namespace: n8n
spec:
  encryptedData:
    values.yaml: AgCKFJ1Dfg8TLSVpnJUx4nmwfQtoBDLEhSZaoj8SN4+Cv/L+6+YXNI8rQx0Y6Evcogm4Ccuqrpcwo8yPnaPkS2k0gGJwGUkmjcLMn1smHG6VerXY0+TyUb2aAvT6CWB+5H5f6Sz3HUbWxVlNj2RWyAepcnuKru/ZZ6YwgCEiPv3PWUHda65fJNFZErqPvz5vRu8MdBpxi8YDzi6JFxlPKT26nyO6ThRZHAn+ctAV88CE4CQqqvyDNsH6eRTDcd8upLVE7jpJbjE+vn6Mt7lkfmgZ32IrAPxA0w6b0KoGrU83Vml0jjQ9aGMhOExzlXb3PNZJqF5UHRbP3PJrR8uJnA2Cgu8SgP365veJcdhRourb/kUbt47sZE24QLLkHODZxVz7AnwXQZXl5kW11FmvC/OWwcm8jQN4RSwvZkQes9XPVVar9rX5FVF64Enve8B3umPxHb7ctCsUcKGqwuHPZ7GO2u1NU/ME66gv2n2IErM+TmYEOrMILooEMrBPfwr7qWQs0UYCuV9yjgDcj4oPcVyiHOD93up20hPcEfZFQ20bwtgVOXXvm9FRmWezTp6jmWVwxSB/3UStYRoPB2yRQnuUCWuetf13ep0q9Osk+3GeIQD207FdvesUlZJ2tQmkfIdc9ubumhDBJg2gk2ZEFd31D5nU6nxM8pmrUW+me5xdn69WbYGhY/6s9ENDwV7CdwYV3L69xZ2iQTQPh9M+fZ8QHSdT+nky0vh3e+o4xU0YC159uaUjL53ZB2MTLaf4jqkxsC98wrDAYs55iZObKFOYso5dMhdEPs92EV4x5SADNRlRtMuPO7LqHwDwsSmddUxQAF7FbcQLlVcNCOV22rlYXkNXv9j569OkVLgaKYIi/0FHmhSs4jA1FswdTj3TJhF/fg==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secret-values
      namespace: n8n