apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin-secret
  namespace: pihole

spec:
  encryptedData:
    password: AgAopjKgHcxAJzlyFiqbJ+kvE8aZEFGKSns0hy9dtbVnK1oFHP+DB2H6hNc1KJPDCAA9NGajIRs+ZBQM/gvi2WPKdr5FmiTD4tZfU5GdpYRa7njk2BqzyzNxw9OzENG6U+6vY+gWZ9q+ZVvnH/LA++rMrlztdtbhh+d/nYVq45pq33OKBAf6E4CQ8+cdf5aehIqi/kHt01nQ7aLsnCuSHDmhiabgv7ypaiwvLdVRwb3IFyKPQVKpUZGChN236Iha8MFQ5bXC3E+ugnLzeWxNeBazEnuF7dcWU2wVqBxAw3p2+o7Yse/oJ9WFZ6yFQ5j31pj494qTHsUMTufbVOOi2UuHgIbMcIOggFWJ8Nu39z5vKlphvnxizrbrSS3NIbGcJJB+LKQxl4uMhqkl7S3Fjo0qYpd5D053p1UfsW7KKfpNnQAAvdaeCIippGxEEX48oXdQJJ3V73lyrVfcfeSGOhfK+2MPlO/Tii4aI8xbXeMhAC0Noqy6ixbkt36k/Ci5MyXKDuznOenKBboL0ODsIVrI40vOmvfyGR2lnNNHoLKFlTa/W2kDIjzlRfklU8DCp3uUio4+y78fnd1B9YPaMWLltH0RzimWGtF2Y6DXNWsmM3vtl051I+u8AtlnHH3a+I4P5wLuBOTGOWq3TVry19sUS5BK1l3spVP371ibKMnfel84VIQ6dvPcMtqfCwd+EP0iSYVGy0dzUDddVQ==