apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  encryptedData:
    password: "AgAbto6j5KsSBqlYgut5eM3/IGhadET9kmlEOG34maEyq2BxO+sxEP0clQQqdHtBNdBleDEJ0tXt5KbSUxZeDAZjpbAVO20QNg9pu7AFZVW9c1tbjPxuPp6p8XR+T/aOU5crpKcpOeLtQ7XwmodP+kXhUf1kF9Ncvw9EK9iMVPBFa7LsctQh50BFyg5x7SvmPPj9MSvCaw213o5hqsDqmDSXaRLqE62JxoQ39M0NPAA+o25aHwopoyVb+wFpk/141xauFrgMKo+ZgYjtK8jbGY9QF2Al4we+U4ERFzs1QcY7t4bWgoMPODfRQhTg50rOiUnvw5/qZDsOlU/oRxCJfSspD6MuO7HYng+2NstcLmpylrrmKDgIBkfsfjIEQPICFL1FvHoU0eSuQndL3A6tL7UghXEiYIUkst2UAmFXgTxvu14K6LsFZZwe93Lw7u4t9ZrhmqyMhlmhjLdYvfuQQdhc3AXhcaLmeWlwP+ZSBZQbRV3v542GxwnX0nYu0glmgXdRbZQ4AkfxZO/9pAUiFj1dG2jJUWk2nBgfSUUU8gizInm91EQBWNt9nckgGmndIBd/gRr76my3VfGhYNFTZGhMibA0yOOA0zGAkk49j7TBfULEBQWLfYDElgKcx1GQf3lceB65Irzflk3qGZyB4tM6Hgn+yajzZfcPBZR739SAsWoIyH7oT1ILu3mksAJgXn/QuUPaPbf7jZy9Lgk3+to="
  template:
    metadata:
      name: pihole-admin
      namespace: pihole
