apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-values
  namespace: forgejo

data:
  values.yaml: |
    gitea:
      admin:
        username: johan
        password: admin
      config:
        indexer:
          REPO_INDEXER_ENABLED: true

    persistance:
      enable: true
    storageClass: longhorn
    size: 10Gi

    ingress:
      enabled: true
      hosts:
        - host: forgejo.lan
          paths:
            - path: /
              pathType: Prefix

    service:
      ssh:
        type: LoadBalancer