apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-values
  namespace: grafana
data:
  values.yaml: |
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 1Gi

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-server.prometheus.svc.cluster.local
            isDefault: true

    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: grafana

    ingress:
      enabled: true
      hosts:
        - grafana.lan
