---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret-values
  namespace: grafana
spec:
  encryptedData:
    values.yaml: AgBWOMkGWCCsnft5atF9ToJOZKYLprI1JNEvVY+a+pkSwDI1yhDTh4790vWd4qScTfIx35uC5387N1GMdw5g9Dkri/WDXbn7uZ41xWXZ3n/MXAmHeQKkWshr1qjs9piWmLUPRzBgXSvEQCT2RX1YF/+nBNghKi8wCBQTL1+7aEu0ekss/yy/NDFFV6JILhhpSSUKXfmqWEfPVlpi3KZbCnDOmvRjjn3awObpt/sdo9uzXDH8bYaWPdZEEBlcGcLBMfTHpIpohPcak91PTn8lFuVo9jwq5OfsZXDI06gxkAnS32ET2aKjP4t5zfNvDz1S+Mwpr+xYflN6qCtDJheWt1hqpR2Xzg3gt/vbrokis1MCMmW0RtNEGbs6pUPp2FPg6qPgwGZZt50y8dnJLhVgF/9atir+chZVZUcHaHQZ4rJ+KwlIhr3tRP3XRDuSF4rngmpoIe4W+SuO4eTJhHs4wK77+3TEf52u1KdVBz5zUO+awZqeUQPhT0E6DYHvuM0sn4HEUrVbMrDoyiK11LqtDq4JQkxqdXz54Gip/0ZT6/Kio6a7k6dY0QARRqI6AQKX05pYSm2GRSVVZDh2Hk61ghrOpoFMIvRqwNLJAZsRMRG9hyCuyph55ryJTcht746gG12mCbouUiLwn0Y3oKEZ9ORXRXJv1O4VYP+n9GD3Weo4x3QhiQU3TieFhBGr0nwuwHvKiNCVTpFJLhjYxU75L9RF4iR237wFo5HSpfP9
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret-values
      namespace: grafana
