apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-values
  namespace: prometheus
data:
  values.yaml: |
    alertmanager:
      enabled: false

    prometheus-pushgateway:
      enabled: false

    server:
      retention: "7d"

      persistentVolume:
        enabled: true
        storageClass: longhorn
        size: 10Gi

      ingress:
        enabled: true
        hosts:
          - prometheus.lan

    extraScrapeConfigs: |
      - job_name: forgejo
        static_configs:
          - targets:
              - forgejo-http.forgejo.svc.cluster.local:3000
        metrics_path: /metrics

      - job_name: pihole
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [pihole]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_name]
            regex: exporter
            action: keep
          - source_labels: [__meta_kubernetes_pod_ip]
            action: replace
            target_label: __address__
            replacement: "$1:9617"
