---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-registry-secret
  namespace: plan-assistant
spec:
  encryptedData:
    .dockerconfigjson: AgBlv6TAd02Grdwyh6wqvKpoXz0OSggWHWdQ5srEoFRCR65WL/t7iPDiBDompQ0q+yHu5Hvln3C2Nhn3NTdYeHAxv6RnX9dyG4gcdplZWiLhg6VavNbW+SuRXrX9nQtGIGm1rDNIleJxBq1EwgU6BUN5BdSMO+1x/q1bqCwFYnT6hWCTF92oGP9HEpPjhf451IB16OZpO+JS9LIxyiwQUfqkm0Wuc3ZEkoOWYzwqQtvIuRzO4IgS7x4uIkjy5ztkR1EKqLZIQm66N66lj43ax9N3KfeVhbzruBTPUT1JQ7zblWbr36N6csl8FgBRXoJZnzOVUx6gl8cPyuKdOwLpQYUTVITeTdK4f6ga/y4kIUzw1Wou5I7XHPSbsv0JotLpD4zsbYkSNu8wwyfJTUeR34Co/V2cv21He6Oy52eZpTiRu/izUocmHlwu2ZDAMEsx4ch24SAY+MblAUltI2tmpVqDAC8Q+BdABrQ5OeSz4lztKkQC83vSSTzR+fBuE3Wxgk/EJRyZSMhG2DZRWwFGy54DRd6fGcfth2TfUjlV5jyOYjBhaesKIIshR/dJTfK9YKFnYUBVqdGh7DvTOLskxr0Uvw2pPrY+ZraxvX+mYdDC3meQKrDlR1TDWTh4BPp6RNzKkL51JSQzSlW4N/ssJJxaC4aoPbvpzI5s9cdONTx6234gxb+WDuGQ7IM03hdBUEVWbtl+47ORcFp9t/UuPFuPeICUJe9WLcHD3rRAj3TLYV3QRQl8gEfyhHVn/elKhrInVOrTqHGDHxqZuxZzuLGQfZtwpuA21ude2J01tqJlq6X8jYmdOtpVwtF1ErCy8spb4uST0NAxeCUEbcO2pusC8GiSnroCmLhb9SpzHk2+Ymj66OqJNfdVRbdxorSUuEY5X6ZQMmypV0NtQgbCYLnWI9QqBQaAdthZriqOlER3Ui5dl0eyeg==
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-registry-secret
      namespace: plan-assistant
    type: kubernetes.io/dockerconfigjson
