apiVersion: v1
kind: Service
metadata:
  name: plan-assistant-backend
  namespace: plan-assistant
spec:
  type: ClusterIP
  selector:
    app: plan-assistant-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: plan-assistant-frontend
  namespace: plan-assistant
spec:
  type: ClusterIP
  selector:
    app: plan-assistant-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: plan-assistant-postgres
  namespace: plan-assistant
spec:
  type: ClusterIP
  selector:
    app: plan-assistant-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
