apiVersion: v1
kind: Secret
metadata:
  name: forgejo-registry-secret
  namespace: cycling-training-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiZ2hjci5pbyI6IHsiYXV0aCI6ICJhM1poY201aVpYSm5MV3hoWW5NNloyaHpYekpsUVdzNWRGRjFTRVYxVEc1VFlXTndaVlUwV0RCb1RtMXVjbVJIU3pJelZEWnZSZz09In19fQ==
